### ISSUE TITLE
User Story #1

### ISSUE THREAD

**Issue by rraj13** [mapachurro/canoe#1]
User is looking to go a new destination based on weather. For example, they are living in Cleveland and have only grey, cold deathful weather and wants some sunshine! 

1) Current location API grabs user's location and set's flight api initial location
2) User enters what type of weather they are seeking (sunny in this case, - depends on the API categories)
3) User clicks enter
4) Flight API generates 5 flights that are within the next 24 hours to locations are have sunny weather the following day
5) App displays 5 flights and redirects user to relevant flight booking site

**Comment by bbillman89** [comment]
party
